### ISSUE TITLE
Meta lattice issue

### ISSUE THREAD

**Issue by thofma** [thofma/Hecke.jl#557]
- [ ] Cache a pseudo HNF and improve equality work for number field lattices (#541, @thofma)
- [ ] For creation of lattices without ambient space we want to allow *either* provide basis (pseudo)-matrix (then the ambient space will have the identity as gram matrix) or provide a Gram matrix (via `gram = `) (then the lattice is free and the provided matrix is the Gram matrix of the ambient space). We retire the `gram_ambient_space` keyword. (@thofma)
- [ ] Make the quadratic (hermitian) lattice data base use the artifact system (@thofma)
- [ ] Test and document the databases (requires previous step).
- [ ] Move `LocMultGrpModSquMap` out of Misc to its "proper" place (@thofma).

**Comment by StevellM** [comment]
For lattice constructors, in both hermitian and quadratic cases, an idea will be to allow the following constructors:

1.  If the ambient space `V` is fixed by the user, then one can:

-   Construct a lattice in this ambient space with a given pseudo matrix: `lattice(V::AbsSpace, B::PMat)`; 

- Construct a lattice in this ambient space with a given basis matrix: `lattice(V::AbsSpace, basis::MatElem)`;

-  Construct a lattice in this ambient space with a given set of generators: `lattice(V::AbsSpace, gens::Vector{Vector{}})`;

- Construct the trivial lattice in this ambient space: `lattice(V::AbsSpace)`.

2. If the ambient space is not specified, then one should mentioned the base algebra `F`, with the possibility to specify the gram matrix `gram` for the ambient space (which will be the identity if not specified, i.e. `gram = nothing`). This specification is necessary for the free lattice. Then one can:

-  Construct a hermitian/quadratic lattice over `F` with a given pseudo matrix: `hermitian/quadratic_lattice(F::Field, B::PMat ; gram = nothing)`;

- Construct a hermitian/quadratic lattice over `F` with a given basis matrix: `hermitian/quadratic_lattice(F::Field, basis::MatElem ; gram = nothing)`;

- Construct a hermitian/quadratic lattice over `F` with a given set of generators: `hermitian/quadratic_lattice(F::Field, gens::Vector{Vector{}} ; gram = nothing);

- Construct the free hermitian/quadratic lattice over `F` whose ambient space admits `gram` as gram matrix (in this case, the argument `gram` needs to be specified): `hermitian/quadratic_lattice(F::Field ; gram::MatElem)`.

**Comment by simonbrandhorst** [comment]
> I guess some tasks in the previous list are done ( (6) coverage for hermitian lattices, (12) constructor of lattice with given generators, (15) `isdefinite` function for hermitian spaces, (16) check if a pseudo matrix is of full rank). I add some new tasks that I might do soon:
> 
>     * [ ]  Modify `mass(::ZLat)` to return the mass of the genus of the entry argument.
I disagree here. There mass of `L` is `1/|aut(L)|` this change should be reverted. 

>     * [ ]  Add a method `lll_gram(::ZLat)` for arbitrary `ZLat` which calls the appropriate methods depending on the definiteness of the entry argument.
We have this method it is called `lll(::ZLat)`. Maybe it is hard to discover?

**Comment by fieker** [comment]
Lll_gram is harder to find and reduces a gram matrix. I'd suggest to future
proof by adding reduce without requiring a specific algorithm

**Comment by simonbrandhorst** [comment]
Agreed. There is `reduce` and `reduction` `saturate` and `saturation` is there any consensus on the horizon?

**Comment by fieker** [comment]
On Thu, Mar 28, 2024 at 04:49:13AM -0700, Simon Brandhorst wrote:
> Agreed. There is `reduce` and `reduction` `saturate` and `saturation` is there any consensus on the horizon?
> 
I think reduce (as in map_reduce) is the julia way, Nouns are probabli
magma induced...
